#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

getent group  tor || groupadd -r tor
getent passwd tor || useradd -g tor -r -d /var/lib/tor -s /bin/false tor

passwd -l tor
chown tor:tor /var/lib/tor
chown tor:tor /var/log/tor
chown tor:tor /etc/tor/torrc

# End of file.
