#!/bin/sh -ex
export PATH="/sbin:/usr/sbin:/bin:/usr/bin"

# check for root privileges needed for gl-select
if [ "$(id -u)" != 0 ]; then
	echo >&2 "$0: error: pre-install script requires superuser privilege"
	exit 1
fi

# is gl-select available?
if [ -x /usr/bin/gl-select ]; then
	cat <<EOF

NOTE: With the introduction of GLVND, gl-select is no longer needed.
      This pre-install script will reset gl-select to its default
      xorg setting if needed.  It is recommended that gl-select be
      uninstalled after installing libglvnd and upgrading mesa3d.

EOF
	# is nvidia currently selected?
	if /usr/bin/gl-select status | grep -q 'nvidia.*is selected'; then
		/usr/bin/gl-select use xorg
	fi
fi

# End of file.
